// Code generated by Thrift Compiler (0.16.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"encryption"
)

var _ = encryption.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  i32 lagrange(TPKEPublicKeyThrift PubKey,  S, i32 j)")
  fmt.Fprintln(os.Stderr, "  EncryptedMessageThrift encrypt(TPKEPublicKeyThrift PubKey, string m)")
  fmt.Fprintln(os.Stderr, "  string combineShares(TPKEPublicKeyThrift PubKey, EncryptedMessageThrift em,  shares)")
  fmt.Fprintln(os.Stderr, "  string decryptShare(TPKEPrivateKeyThrift PrivKey, EncryptedMessageThrift em)")
  fmt.Fprintln(os.Stderr, "  DealerThrift dealer(i32 players, i32 k)")
  fmt.Fprintln(os.Stderr, "  string aesEncrypt(AESKey key, string raw)")
  fmt.Fprintln(os.Stderr, "  string aesDecrypt(AESKey key, string encMes)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  var cfg *thrift.TConfiguration = nil
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransportConf(trans, cfg)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := encryption.NewTPKEServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "lagrange":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "Lagrange requires 3 args")
      flag.Usage()
    }
    arg32 := flag.Arg(1)
    mbTrans33 := thrift.NewTMemoryBufferLen(len(arg32))
    defer mbTrans33.Close()
    _, err34 := mbTrans33.WriteString(arg32)
    if err34 != nil {
      Usage()
      return
    }
    factory35 := thrift.NewTJSONProtocolFactory()
    jsProt36 := factory35.GetProtocol(mbTrans33)
    argvalue0 := encryption.NewTPKEPublicKeyThrift()
    err37 := argvalue0.Read(context.Background(), jsProt36)
    if err37 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    arg38 := flag.Arg(2)
    mbTrans39 := thrift.NewTMemoryBufferLen(len(arg38))
    defer mbTrans39.Close()
    _, err40 := mbTrans39.WriteString(arg38)
    if err40 != nil { 
      Usage()
      return
    }
    factory41 := thrift.NewTJSONProtocolFactory()
    jsProt42 := factory41.GetProtocol(mbTrans39)
    containerStruct1 := encryption.NewTPKEServiceLagrangeArgs()
    err43 := containerStruct1.ReadField2(context.Background(), jsProt42)
    if err43 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.S
    value1 := argvalue1
    tmp2, err44 := (strconv.Atoi(flag.Arg(3)))
    if err44 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.Lagrange(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "encrypt":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Encrypt requires 2 args")
      flag.Usage()
    }
    arg45 := flag.Arg(1)
    mbTrans46 := thrift.NewTMemoryBufferLen(len(arg45))
    defer mbTrans46.Close()
    _, err47 := mbTrans46.WriteString(arg45)
    if err47 != nil {
      Usage()
      return
    }
    factory48 := thrift.NewTJSONProtocolFactory()
    jsProt49 := factory48.GetProtocol(mbTrans46)
    argvalue0 := encryption.NewTPKEPublicKeyThrift()
    err50 := argvalue0.Read(context.Background(), jsProt49)
    if err50 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.Encrypt(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "combineShares":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "CombineShares requires 3 args")
      flag.Usage()
    }
    arg52 := flag.Arg(1)
    mbTrans53 := thrift.NewTMemoryBufferLen(len(arg52))
    defer mbTrans53.Close()
    _, err54 := mbTrans53.WriteString(arg52)
    if err54 != nil {
      Usage()
      return
    }
    factory55 := thrift.NewTJSONProtocolFactory()
    jsProt56 := factory55.GetProtocol(mbTrans53)
    argvalue0 := encryption.NewTPKEPublicKeyThrift()
    err57 := argvalue0.Read(context.Background(), jsProt56)
    if err57 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    arg58 := flag.Arg(2)
    mbTrans59 := thrift.NewTMemoryBufferLen(len(arg58))
    defer mbTrans59.Close()
    _, err60 := mbTrans59.WriteString(arg58)
    if err60 != nil {
      Usage()
      return
    }
    factory61 := thrift.NewTJSONProtocolFactory()
    jsProt62 := factory61.GetProtocol(mbTrans59)
    argvalue1 := encryption.NewEncryptedMessageThrift()
    err63 := argvalue1.Read(context.Background(), jsProt62)
    if err63 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    arg64 := flag.Arg(3)
    mbTrans65 := thrift.NewTMemoryBufferLen(len(arg64))
    defer mbTrans65.Close()
    _, err66 := mbTrans65.WriteString(arg64)
    if err66 != nil { 
      Usage()
      return
    }
    factory67 := thrift.NewTJSONProtocolFactory()
    jsProt68 := factory67.GetProtocol(mbTrans65)
    containerStruct2 := encryption.NewTPKEServiceCombineSharesArgs()
    err69 := containerStruct2.ReadField3(context.Background(), jsProt68)
    if err69 != nil {
      Usage()
      return
    }
    argvalue2 := containerStruct2.Shares
    value2 := argvalue2
    fmt.Print(client.CombineShares(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "decryptShare":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "DecryptShare requires 2 args")
      flag.Usage()
    }
    arg70 := flag.Arg(1)
    mbTrans71 := thrift.NewTMemoryBufferLen(len(arg70))
    defer mbTrans71.Close()
    _, err72 := mbTrans71.WriteString(arg70)
    if err72 != nil {
      Usage()
      return
    }
    factory73 := thrift.NewTJSONProtocolFactory()
    jsProt74 := factory73.GetProtocol(mbTrans71)
    argvalue0 := encryption.NewTPKEPrivateKeyThrift()
    err75 := argvalue0.Read(context.Background(), jsProt74)
    if err75 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    arg76 := flag.Arg(2)
    mbTrans77 := thrift.NewTMemoryBufferLen(len(arg76))
    defer mbTrans77.Close()
    _, err78 := mbTrans77.WriteString(arg76)
    if err78 != nil {
      Usage()
      return
    }
    factory79 := thrift.NewTJSONProtocolFactory()
    jsProt80 := factory79.GetProtocol(mbTrans77)
    argvalue1 := encryption.NewEncryptedMessageThrift()
    err81 := argvalue1.Read(context.Background(), jsProt80)
    if err81 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.DecryptShare(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "dealer":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Dealer requires 2 args")
      flag.Usage()
    }
    tmp0, err82 := (strconv.Atoi(flag.Arg(1)))
    if err82 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    tmp1, err83 := (strconv.Atoi(flag.Arg(2)))
    if err83 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.Dealer(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "aesEncrypt":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "AesEncrypt requires 2 args")
      flag.Usage()
    }
    arg84 := flag.Arg(1)
    mbTrans85 := thrift.NewTMemoryBufferLen(len(arg84))
    defer mbTrans85.Close()
    _, err86 := mbTrans85.WriteString(arg84)
    if err86 != nil {
      Usage()
      return
    }
    factory87 := thrift.NewTJSONProtocolFactory()
    jsProt88 := factory87.GetProtocol(mbTrans85)
    argvalue0 := encryption.NewAESKey()
    err89 := argvalue0.Read(context.Background(), jsProt88)
    if err89 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := []byte(flag.Arg(2))
    value1 := argvalue1
    fmt.Print(client.AesEncrypt(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "aesDecrypt":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "AesDecrypt requires 2 args")
      flag.Usage()
    }
    arg91 := flag.Arg(1)
    mbTrans92 := thrift.NewTMemoryBufferLen(len(arg91))
    defer mbTrans92.Close()
    _, err93 := mbTrans92.WriteString(arg91)
    if err93 != nil {
      Usage()
      return
    }
    factory94 := thrift.NewTJSONProtocolFactory()
    jsProt95 := factory94.GetProtocol(mbTrans92)
    argvalue0 := encryption.NewAESKey()
    err96 := argvalue0.Read(context.Background(), jsProt95)
    if err96 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := []byte(flag.Arg(2))
    value1 := argvalue1
    fmt.Print(client.AesDecrypt(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
