
LOG_DIR = './logs'


LOG_PATH = LOG_DIR + '/honeybadger_test_{}_{}_{}_{}_{}_{}.log'
LOGGER_NAME = 'honeybadger_test_logger'
NUM_OF_NODE_OPTIONS = [4, 6]
NUM_OF_IDENTICAL_INPUTS_OPTIONS = [0, 2, 4, 6]

NUM_OF_INPUTS_IN_ITERATION = 3
INPUT_SIZES = [2, 1024, 1024*1024]
SET_NUM_OF_NODES = 6
SET_NUM_OF_IDENTICAL_INPUTS = 2
SET_INPUT_SIZE = 2 # TODO: Change to 1024*1024
